# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joystick',
            name='angle',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='joystick',
            name='left_buttons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joystick',
            name='pedal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joystick',
            name='right_buttons',
            field=models.IntegerField(default=0),
        ),
    ]
